package dev.ranieri.utilities;

// Logging is the process of storing important information generated from your program
// typically it is just a text file
// the exact format is up to your configuration/preference

// Logging Levels. general types of logs generated by a program

// DEBUG - log generating while debugging/testing
// INFO - logs generated when important things happend i.e. a new user is create
// WARNING - logs generated when something occurs that is not an immediate issue but could be (failed login attempts)
// ERROR - logs generated when errors slash exceptions occurs
// log DO NOT go to your database. Typically just stored in a local file
// logs are not application data

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Date;

public class Logger {


    public static void log(String message, LogLevel level){
        // LOG LEVEL + message + TimeStamp
        String logMessage = level.name() +" " +  message + " " + new Date() + "\n";

        try {
            Files.write(Paths.get("C:\\Users\\AdamRanieri\\Desktop\\PleastViewLibrary\\applogs.log"),
                    logMessage.getBytes(StandardCharsets.UTF_8),
                    StandardOpenOption.APPEND);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }



}







